name: test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: macos-latest

    strategy:
      matrix:
        target: [brew.0, brew.1, brew.2, deploy]

    steps:
    - name: uninstall brew
      run: echo y | ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)" || true

    - uses: actions/checkout@v1

    - name: Run test
      run: make test.${{ matrix.target }}
