name: test

on: [pull_request]

jobs:
  test:
    runs-on: macos-latest

    strategy:
      matrix:
        target: [tap, brew, cask]

    steps:
    - name: uninstall brew
      run: echo y | ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)" || true

    - uses: actions/checkout@v1

    - name: Run test
      run: make test.${{ matrix.target }}
